Preview for excel file/files
vlrsmlkv/pu-2 pull request #10
Opened 2021-10-11 18:31 UTC by vlrsmlkv

Realize opportunity to see all output data witout downloading

Place all the sheets in order under the control buttons. And let the general sheet be at the top.

And dont forget that preview should be the same structure as downloaded file/files

2021-11-05 17:30 UTC, OUghTMS requested changes

2021-11-05 17:30 UTC, OUghTMS commented on src/App.jsx
> +  useEffect(() => setProcessedData(null), [fileData])
move into onChange for fileData

2021-11-05 17:30 UTC, OUghTMS commented on src/components/PreviewProcessedData.jsx
> +const PreviewProcessedData = ({isDisabledShowButton, data, onShowClick, headerCells, isVisibleButtons}) => {
line break

2021-11-05 17:30 UTC, OUghTMS commented on src/App.jsx
> +          <button className="download-button"
???

2021-11-07 18:19 UTC, vlrsmlkv commented on src/App.jsx
> +          <button className="download-button"
really done

2021-11-07 18:20 UTC, vlrsmlkv commented on src/components/PreviewProcessedData.jsx
> +const PreviewProcessedData = ({isDisabledShowButton, data, onShowClick, headerCells, isVisibleButtons}) => {
done

2021-11-07 18:35 UTC, vlrsmlkv commented on src/App.jsx
> +  useEffect(() => setProcessedData(null), [fileData])
done i guess

2021-11-14 11:44 UTC, OUghTMS requested changes

2021-11-14 11:44 UTC, OUghTMS commented on src/components/FileField.jsx
> +    setProcessedData(null);
net blat ne suda

2021-11-14 11:44 UTC, OUghTMS commented on src/App.jsx
> +  useEffect(() => setProcessedData(null), [fileData])
net

2021-11-18 21:36 UTC, vlrsmlkv commented on src/components/FileField.jsx
> +    setProcessedData(null);
fixed

2021-11-18 21:36 UTC, vlrsmlkv commented on src/App.jsx
> +  useEffect(() => setProcessedData(null), [fileData])
fixedfixed

2021-11-28 18:46 UTC, OUghTMS approved these changes

2021-11-28 18:46 UTC, merged